version: "3.9"
   
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ${HOME}/neo4j/data:/data
      - ${HOME}/neo4j/logs:/logs
      - ${HOME}/neo4j/import:/var/lib/neo4j/import
      - ${HOME}/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}//${NEO4J_PASSWORD}
  main:
    build: .
    container_name: main
    volumes:
      - .:/code
    tty: true
    